### ISSUE TITLE
Calculating large factorials hangs the browser

### ISSUE THREAD

**Issue by mendes5** [viniciusmeneses/rubiks-cube-calculator#1]
Just an nice to have, but is not too difficult to implement:

The algorithm used is very CPU intensive and runs on the main thread, which gives a bad user experience as his entire screen would freeze.

I think that the processing logic could be moved to an [WebWorker](https://developer.mozilla.org/pt-BR/docs/Web/API/Web_Workers_API), so, would be possible to add an loading spinner, or even an progress bar using [`self.postMessage()`](https://developer.mozilla.org/pt-BR/docs/Web/API/Worker/postMessage#Transfer_Example) inside the workers.

**Comment by viniciusmeneses** [comment]
Thanks for reporting the problem! I did a PR to merge the changes and add the web worker.
